#!/bin/bash

FOLDERS_TO_UPDATE=( /usr/Scripts )
FOLDERS_TO_CHECK=()


if [[ $1 == -a ]]
then
 # Get all the users to update their documents
 cd /home
 USERS=$(ls -d -- */)
 for USER in $USERS
 do
    # Save all the user's documents folders
    FOLDERS_TO_CHECK+=("/home/$USER""Documents")
 done
 # Loop through all their folders in documents
 for to_check in $FOLDERS_TO_CHECK
 do
    echo "$to_check"
    cd $to_check
    for folder in "$(ls -d -- */)"
    do
        /usr/bin/Scripts/update "$FOLDERS_TO_CHECK/$folder"
    done
 done
 # Update any specific directories
 for to_update in $FOLDERS_TO_UPDATE
 do
    /usr/bin/Scripts/update $to_update
 done
# Just a regular single folder update
else
  if [ $# -eq 0 ]
  then
      if [ -d .git ]
      then
          git add *
          git commit -a --allow-empty-message -m ''
          git pull
      else
          echo "Please call 'update' on or in a git repo"
      fi
  else
      for FOLDER in $@
      do
          echo "Updating: $FOLDER"
          cd $FOLDER
	        git add *
          git commit -a --allow-empty-message -m ''
          git pull
	  cd ..
          echo ""
          echo ""
      done
  fi
fi
